name: Deploy to WordPress.org
on:
  push:
    tags:
    - '*'
jobs:
  tag:
    name: Build and deploy plugin
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Enviroment
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
    - name: Install Packages
      run: composer install --optimize-autoloader --no-dev   
    - name: WordPress Plugin Deploy
      uses: varunsridharan/action-wp-org-deploy@master
      with:
        WORDPRESS_PASSWORD: ${{ secrets.WORDPRESS_PASSWORD }}
        WORDPRESS_USERNAME: ${{ secrets.WORDPRESS_USERNAME }}
        SLUG: wc-m-pesa-payment-gateway
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
